### ISSUE TITLE
搬瓦工debian9网卡识别错误，不能启动

### ISSUE THREAD

**Issue by BrunuhVille** [yushum/wireguard_game#2]
root@bwh-gia:~# wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
Line unrecognized: `eth1-jMASQUERADE'
Configuration parsing error
[#] ip link delete dev wg0
实际网卡为eth0，但是脚本安装时错误识别成eth1，导致不能启动

**Comment by yushum** [comment]
搬瓦工的VPS比较特别，直接把第36行改成eth0

**Comment by BrunuhVille** [comment]
> 搬瓦工的VPS比较特别，直接把第36行改成eth0
改动之后卸载重启安装，未解决
root@bwh-gia:~# wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.16.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a tun.wg0 -m 0 -x
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o  -j MASQUERADE
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.
[#] resolvconf -d tun.wg0 -f
[#] ip link delete dev wg0

root@bwh-gia:~# wg
wg命令无显示，没有启动
root@bwh-gia:~# cat /etc/wireguard/wg0.conf
[Interface]
PrivateKey = IOmDCvp6bXaK5sKjflb5w1WvXpp5nBBMe4l4g5L/dFE=
Address = 172.16.0.1/24 
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o  -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o  -j MASQUERADE
ListenPort = 43555
DNS = 8.8.8.8
MTU = 1420
MASQUERADE前没有网卡名，原脚本是eth0 eth1两个，改动36行后 一个也没有了

**Comment by BrunuhVille** [comment]
将脚本中3处eth改为eth0，可正常安装，问题解决，感谢

**Comment by yushum** [comment]
42 43行的$eth改成eth0后就可以删掉36行了
